version: 1.0.0-{build}

configuration:
  - conf1
  - conf2

platform:
  - platform1
  - platform2

environment:
  var1: something-var1
  var2: something_var2
  matrix:
  - var_env1_0: ya
    var_env1_1: yaa
  - var_env1_0: yo
    var_env1_1: yoo

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  

init:
  - echo var1 %var1% %CONFIGURATION% %PLATFORM%
  - echo var_env1_0 %var_env1_0% %something-var1%
  - echo number %APPVEYOR_BUILD_NUMBER%
  - echo version %APPVEYOR_BUILD_VERSION%

build: off

before_build:
  - echo before build
  - echo var1 %var1%
  - echo var_env1_1 %var_env1_1%
  - type AssemblyInfo.cs

build_script:
  - echo var2 %var2%
  - echo var_env1_1 %var_env1_1%

after_build:
  - echo after build
