configuration:
  - conf1
  - conf2

platform:
  - platform1
  - platform2

environment:
  var1: something_var1
  var2: something_var2
  matrix:
  - var_env1_0: ya
    var_env1_1: yaa
  - var_env1_0: yo
    var_env1_1: yoo
  

init:
  - echo VAR1 %something_var1%
