version: 1.0.0-$(APPVEYOR_BUILD_NUMBER)

configuration:
  - conf1
  - conf2

platform:
  - platform1
  - platform2

environment:
  var1: something_var1
  var2: something_var2
  matrix:
  - var_env1_0: ya
    var_env1_1: yaa
  - var_env1_0: yo
    var_env1_1: yoo
  

init:
  - echo var1 %var1% %CONFIGURATION% %PLATFORM%
  - echo var_env1_0 %var_env1_0%
  - echo number: %APPVEYOR_BUILD_NUMBER%
  - echo version: %APPVEYOR_BUILD_VERSION%

build: off

before_build:
  - echo before build
  - echo var1 %var1%
  - echo var_env1_1 %var_env1_1%

build_script:
  - echo var2 %var2%
  - echo var_env1_1 %var_env1_1%

after_build:
  - echo after build
